EKS deployment orchestration iteration 1 on day 05
EKS deployment orchestration iteration 2 on day 05
EKS deployment orchestration iteration 1 on day 06
EKS deployment orchestration iteration 2 on day 06
EKS deployment orchestration iteration 1 on day 07
EKS deployment orchestration iteration 2 on day 07
EKS deployment orchestration iteration 1 on day 08
EKS deployment orchestration iteration 2 on day 08
EKS deployment orchestration iteration 1 on day 09
